version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_board
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/michaelptacek05/message-board-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/message_board
      NODE_ENV: production
    ports:
      - "3001:3001"

  frontend:
    image: ghcr.io/michaelptacek05/message-board-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: https://messages.michealptacek.com
      NEXT_PUBLIC_SOCKET_URL: https://messages.michealptacek.com:3001
    ports:
      - "3000:3000"

volumes:
  postgres_data:
